version: '2'

services:

  static:
    build: .
    environment:
      VIRTUAL_HOST: ''
      VIRTUAL_PORT: '80'
      LETSENCRYPT_HOST: ''
      LETSENCRYPT_EMAIL: 'status@ecobytes.net'
    volumes:
      - ./content/:/var/www
      - ./lighttpd.conf:/etc/lighttpd/lighttpd.conf
    expose:
      - 80
    networks:
      - frontend-web

networks:
  frontend-web:
    external: true
